server:
  port: 8081

spring:
  application:
    name: e-submission
  data:
    cassandra:
      contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
      keyspace-name: ocds
      port: 9042
      username: caclient
      password: brT4Kn27RQs

ocds.prefix: ocds-t1s2t3