server:
  port: 8080

spring:
  application:
    name: e-submission
cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK

eureka:
  client:
    enabled: false

ocds.prefix: ocds-t1s2t3