server:
  port: 8080

spring:
  application:
    name: e-submission
  data:
    cassandra:
#      contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
      contact-points: 10.0.10.104 ,10.0.10.105,10.0.10.106
      keyspace-name: ocds
      port: 9042
      username: caclient
      password: brT4Kn27RQs

ocds.prefix: ocds-t1s2t3