server:
  port: 8080

spring:
  application:
    name: e-submission
  data:
    cassandra:
      contact-points: 10.0.10.104,10.0.10.105,10.0.10.106
      keyspace-name: ocds
      username: caclient
      password: brT4Kn27RQs

eureka:
  client:
    enabled: false

ocds.prefix: ocds-t1s2t3